# Generated by Django 5.1.1 on 2024-12-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
